// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdW3PctpL+KyzuPjhVI43ixHnQ09pyLOusc6yy7GSrfFRTGLJnBhEJMAAoS3bpv2/h",
	"RoIkwOFcNUr8kIo1BBpA99c3sAF+ixOaF5QAETw+/RbzZAE5Uv9EicC3WNzLfxeMFsAEBv2kKC5ey3+I",
	"+wLi05gLhsk8HsV3RxQV+CihKcyBHMGdYOhIoLnq9SenJD6VnSc4jR8eRvKfGU6QwJT8G+WwAUVLZkIk",
	"HUk7WSBCINuEriHh0MwQ5w41TATMgcXyEQMkIP2oHs8oy5GIT+MUCTgSOId4tNoM0qkcX9OcCB6PqjnV",
	"v8kZzRktN5CF6m6lof7YhF+aWsUtnHYJyZ8JF4gksP6sLQU7cQ63wAxQu5K5Bcax7NeZy8MoZvBXiRmk",
	"8elnOd+RgXbNWFeyFgDOiDX5Lppdjjbx2GDCdQUNOv0TEiHnbFXvEs3Bo376qfkLC8jVP/6bwSw+jf9r",
	"XGv02KjzuNLlh2o0xBhSfye0JMLPO0EFys5Cz1v8cxpboiN3rt6FFsUZJTM8764yBZ4wXAi/7EYx8SL1",
	"YSTJpGUiJhp/pMwyNM0gPhWshNESDCiigYla4XanamQ7XBymg1ca2zUkfrOxjLcKuMOXo5r7FrPEBHAP",
	"KweCTbfzSWoZLi7Sde2OA6wHr/EgWrld7jbth+HrqEaMywx3igEM8oBFqNG5gk1wIL13s+BO2LtWliwC",
	"ntboTh8TNopOqljCRilmKr28lG0U0zLKvOjbi14H9M2qRI7u3gGZi0V8+uJk5NEQlNwYfPUt1jare6zP",
	"b0NgqU5pxja1qSlwdzJGaB1gDYq6rG2usRZyUS2w+FgfwLGcyJwemV9LTEQ/esJGrebf0gCnNV0zuZq3",
	"Qedn2OC3PVt1fru0OdVEvUsMiThJgPPfEEFzyIGITyxb27QoUpO8ojUpmYYZKsXiN5qunwCVYjHJJQFJ",
	"bQEoBXYl7rO1CWoSE65oSJoZnWOywdpV/2q9GZ3TDShRRYTAlCF+g34PxffD6FkyExvIS9oUp8nLMsVA",
	"krV5KGlMkCViqZ5lGMgGMYiimigi1j/Jny44L4FtICBFFysqlZjkb+/onJZiU8KZotIgfJXQAvhGVLkm",
	"ISkKLNZHu+7ccT8+1e/CzqDZTqGpfo7iOFrusz/AGGUfgBeUcFiaDDX+jN+WOSJHDFAqE51IkYqaQWjH",
	"b6Q06RKO32FyEwkapTQp5ZKVr4ieUfUcZT/4KKnhuqR+VbOQfI9wCkTgGVZ+r99FaWLNENrLLinHNzhr",
	"pcBNpi0QX3idpnzw/MUv/twk9fufoAfm+Cv4fW9n1g13Nwyb6sfJTK1U0pxlSCSIvUxCmSijOby/2tAo",
	"ajKUN4zinjJTlGaY+FmdYi4RfonuM4rSVyi5obOZ03JKaQaIDBzZUJsUmtxkaujJacAtNAKNAD6cn/lr",
	"yARaezKYT1JFQI6eg0ApEugKzwkSJYMPHK0rSktrwi2xCePtYb7CFsh/BeOXIeUv0xyTtZmhSEyQoqE2",
	"+BbIr66+hEGLbtRRhYpMY4q15ELwCoijxT4Hua6mrJqBGAYYLZ8greYdxb+sE7Wm/gfQ2cfALc1P7wHt",
	"LSl3dgEG5hrmn+vPwr4OsDM4hI26JQl/N12kGU7uf0N3nwo5U34J7BIYpopMjgnOyzw+rfcG3Hx1QDKv",
	"qE9ydDcpNf1JAUz+J0d4qMZ/P5vhBN7SkvG1bYQZiypSk4WiVY+gF3VBBLBbtHbsasbQ859gS60e5grN",
	"oJW4rbUKjmZQJ3D6x484h6+UwIaTF5ZMTVnLXtKnpdiQvJazGkUSaw/CfyXSpKabMsjCCQw5ZflpltFS",
	"XJBLRucM+PpYMpQmmEwKS0uZRoaSm4FuZ+neb3e63R2s2kYF2NgBnk+lOggKaEWfOfBjxbLEF5IrBxDa",
	"KXNspzewa5o5Z5/yuXejcvCGZq9B8sb5PrvSxVXdsG0cwlbX0fI+giKo93WbltYtbVkrjnfkCucNxv8y",
	"6GXZMiYHGdVdcGh5QbRdmFcnVwIJ77ukvMhAgF/QKf1CZJwHaf9zuXJvgyrx7T5S73SyLESakrc0S3v2",
	"Of2PSpLCDJMQVc21c4aI8DYZZgsN7+eGzIN3azV2J9MeeVRl8ZUAXI40ON9kc8WZoMQDW9DhbeNtvcnc",
	"fPvZzCS4NAnikqte0ty2kmAnPK/fG+So+CyV5Fh2uJZ/YSLU/7XGXpeYiF9+roYwqdArBuhG8n0wW25b",
	"HX8lgnlrCdxhNlxKZwn2Raknycgw4v7XL83X9n1rtORfNl+LPuZ7O1wMDD5w0Z91Otx72VfIsLNsbR9M",
	"3GYt1PaLlDLExdkCkps3lJloa6vMkPQniRxgMqPMeuJq6E+uif64g6GbfsPKpB56wx1Jdwx3U5Irq9nn",
	"ELeQH5hx2+nB7WZLqpfRVukafN0UoS5MqyvP3DTDMMQPOD8WfGLycG/NvaxGmYmjWpUzHebLu2/MpVcY",
	"XBVkR/UHEI2CpEEesXJGoVhhaJjQqADqm3kgyG0VGDgFJ2716tIqLE8ginPgAuXFQFuxSqllTbs1z6om",
	"oQb3cO6U/C3mgjK8hhzd/t7Ixt+wC999eDoVX5+tUzCgKlxU90mitw/se6b6t2Vm9RYY5kOkXJki26Np",
	"qepV+ARLc7RAH+CvErjoBo/NYqUDrAMztSavMpTcZFgvoQJkR3HWeDFoR5hMqyEOZle6+Xa2j19Oy4dR",
	"PMMZBM1V581nH91mY9WbUvYBEPe9QNe/R18W95FYYB4ZaEWYRzliN5BGiEcoUjSi2jI1dp9ORktKjYe+",
	"WaGUTZie6IN5V73ai8g3kkR3kRcklYAGHuFZZ5mtxUUzyiKxgCgpGQMiooQSAXeihs/KbzcV/RHNpRIU",
	"4l5bGf+rczuIN6Zj/i221ar8VRPXyZSqQqPCX3sfl+tXfEoWrRMBHUXvhmz+WsTahG2/vNCxQI59GG6C",
	"np6OX9Y1qUGNeQy4BWsuu+Jpg85BowGegaFBr8asnUkPvlbeNDP9hkdRTkXw9jfOqtn4lmizFJtTBDQp",
	"sEHUFpZq5hvGvwHWn0d4+AosASKMOGrvTMtp5rhmUubTFc8udcPluDFcd03q3FRSMizur6QU9ZznWCzK",
	"6RmlNxhelmKhFyUjAPWTfc91ahrWc0YF/l9QAqc4TV4BYsAsgan6641d7r/++CixrAaVnkQ9rSkthCgs",
	"nQETkc2609CJ5oxqoBOBEgU/yBHO1G4jJgJhAoz/jzEjRxkm5d0xZfOa9hv9KDqjpnX0TjYyuqenejq2",
	"hkj1bVvO+N+mXlB5WRJpvEa6CJgdV3WDdUNHp0/jk+OT4x8VNwogqMDxafzT8cnxiVILsVAyG6MCj93D",
	"mnMQXfdfoDkmcuiqpSLKtJtK49P40rR4WTcoEEM5CGA8Pv1sBPBXCey+5pE6MEfZpTm58tqKFnlB66dR",
	"72ms3NV9Y7py58ZGy8q9a51buatzfrDT17GNgc4CMWkXa/3X4WZNqbIsVeg5cF5A0t0QLqQRcin11JqE",
	"iQAL0/nRR+haLkbX1CpVeX5yYi2Cqe9z/PP4T5Mc1NSHHKlU3vWhkxbF7zAXlbJFvFTVxJGdjtTpn09+",
	"7uqp1b6IUBHNaEnSRp8XegV9Q+n637qTY+mVFrcN9OdryfC2udW/dv3B5+uHa0lSW51Cv1vzWpw5iOhl",
	"oY67BQyNfjjAyPwd4WMP83mgc645FwCNBwCvkESJ2isZgLCi4F507QAoo7ig3IMNnUJFqCg66DhTj16q",
	"JwOgkWSUwGTGaN5riK+1WQMuXtH0fptSNDGnR4ymsFgl040FNw3sw25R5my+d2aoeb0drHktkzPAns3S",
	"+Fs7MnnQ07MVIc2J6t+9gHytHoUBKQOx3ngo7E+9KO1CoTlVPZ+g0F4s6bMHOYzCDsHH4HMQj8ndfSja",
	"uV76CmFAUawSAViPsRfhFqVHuCax8clXv1ncn4gf0cw3uHAwZl4LYIdm/lO17AMw82P3RHJ/LmxbRnQm",
	"k3MfeG2welbf2LBjDP9zUij3XHnAaFYSGmw5jaBWtZ7VQPsxoX1RsT204o+Mz6qnT9OWNu9UGBY21xzZ",
	"n02t74EIhc2mxW5DZzvIAdnV8bdq121ITG1XML2P1BsQX3S9N1CPvCTdXcTdROt9WHkxoN/jRu39IjwH",
	"8XeS366th+Nt9uXVHj8v6EeQjh+fLoi+e8lw1rE1L7ktvWjN6wAca31IpT9d0e0GJCvn9p6576nKlnBe",
	"nz7yIF26SM3y4QbdtF8Bt84oj5+jKH5EmPRs4au5Ptk0xT3OOsz8zs1692d8zWm1YIKiJLDb9EQPcTA2",
	"dPzN1BIMSUw0huf4FkiEBY9M1wiRNLL3APuSlT0B2x+l1LUSu0lU+jATMmOrWLHGMI+b1awu/3MQfxfh",
	"79YAnVtftUMk1WM8enazOpLsGaynCKZHdbYuxw/D2Zp8YkVn2+i1UsqzsqI0hjpAVz1ulM0GzXXVSiVA",
	"G1jvC/fG7aeieeFiQH3Gaiml5QnX42RtoYVRJt7gTKjS4NXZQpl4z9I1OwNiyWKDwVX/31FWwjrd01Jj",
	"dhvwGFKjussAoXHsNhAnXDT1OmxHg1GAl8JBG7rxt7r2+GGQ1dvA6F04RwKemrlrUmoUbB9GCFwfBPej",
	"u5Lf4EDYimvVWLga6ekgf6zd12RRH6dergjNPsd9iG8e1v6nwj/gGzKcYzHc4e9Didqn+JfqlGofGSjs",
	"UcVaAx+0xk24vTlimG5tLb7WN1Y8/Rh7rYBs59suTS57NKUC+ZUV6nzHOzKhEQ9aPapzsMu1QzXdWvZ5",
	"Vp1v/a4eO/EmmsFLsg5XqBukHl0yhwh6EzoJ51K+IOqNi7NtN4W9du3VdYDfYb8br+C7RdKjAbpZ9NER",
	"7q6dQ3DIQ1QUs28ymbpXZQZVxd6aUrXeVFk6F3V+f99UQ7zDHA++TZvolSuRXSO8Z9BDxvggb2Ahvi13",
	"YHj13R/sR1mWOgSL3X16hPCYB6Au7h04/VV5tuWAurxLS/QfVpnX/6Lkkd9RuLckBYr7rNyGK0PV4zAO",
	"2tsLmvyVepfV06dZq9e8R21YtV7Nkf2VEFTXZAUr9owkhpcRtPpN1yjhs9cAHpDRHX+rvuU7pJDPrqAO",
	"RKruS4v59oZ9fwDifrN4NwV9/ZAKm641ivr2iKSesr710HAO4u8EhV3bq/PaK+4UWe44j17mtx6ydPnV",
	"0wXXI/vrJu8PxV+bmrp9qMCnJvgO1E2P1QW/R0vvXlCXwGRZfd7+ywIYRKj30uUea61uO97/5QyHYLoH",
	"fIff22SFj2Y2rqM+/bbkiuvlHz3u+8Z/t3O/21GSj85WviCio4I97zMFMIKyiAO7BaZVb6ca5ztirzVr",
	"wEaEvsK7sR0RvEuida3JGz3EEPVZ75js0P2ITfYgtl6y0tIefRf6pGjf34uJ+Ol5PPJc+Ku+WrNC+61f",
	"vDyptG3p6K0bhYt6q6qxcHdRzUGuB+jvZevmHY1Zvto711bfPTrEHvUcmrIyyOlt7c0RN2orQ52wun5Q",
	"vVxl3YOu7i1T1atrynW4Pdd+gEGm2MUXuBhg2r1DPl6CYbZinBvEmta8ubxnOIW8oNKIRRVOfuiA5qq6",
	"l+PJIWa9nKNpr9uxS5Pj79U/UBbpBkr/ZNyJybz5dQzn0x/P4Hh+PIr+IwMDFT0CjwhACmk0wxnwey4g",
	"j3hZFJSJSNBogUiaQUTgi5Erj9BMANMjmHdq/4ml6OAO5YW6CNwhPhVsxiuC2F4ffgRkjgkMHmHlb5V4",
	"Y7GHIar8Joxa89mMGuSp1fFZmWX3wS3OC3KLMlzvaz5DLFlgAYkoGUQ55jkSyWIUfWGUzCMHIaMIRHL8",
	"w9K7I5wJLzccV20HtE//Ez4/0Ldt4XwSwLczsdLxgE0q8Le/keD9+sOw/QSHKfvbUOg7LPCpOa/hIVG7",
	"42PgUdcYjzNpgPqLKcUCIt0s4gQVfEFV1VyrAhkljHLe2CgYRa7eyz9Jag0cX3YIgL/TM9tQtit/Uo53",
	"I3PPTfGaHS0WrBQSZ14Se0JCUn11pe/a38g0890eZp/s7pqioGlQ15upp0FG6VUuAGX6OyTeVerHEZC0",
	"oFjV9TaX+VZ3H+JDDan+6WR0jsk4mQYndI7F23IavZfCihKUZVOU3ETPzM85TSGiJLvvho3vJOWz6aCp",
	"tqgXjErMejz7TyfPfUF4ihkkKlSiDMvUMMvuraOHNPr04d2Q20p0mx89ppGgUiwow19h5V0e2frHrQFQ",
	"Ef1QS7T7nRgqIiwjwByIXLp0Ve8vXp9FcgVKXH04UBGS+mY+vYFwsaJtFv3rj48R0vZF9YieqbF6UPG7",
	"6fpRDTAEG9VgeoRmHucRFjZxngyp7grpkHXPgxCFUZtBwvgC0wWlNyos8xZlGGKm3WCd/MPQ9cdpC0D6",
	"vLOJ1P7v6G05PbrCc4Kkw1wrn+vSPFdu4OjXWyBi+xsBin8VX5qe7wno4u2PJiINi1591jTsJd7Lx3Ff",
	"sCzgTozv8mz4chtfUl0SHHemNyg2bvkERePDkNumzKwiPKuyO46/qndAgtIoQ2zuY/XDw/8HAAD//25J",
	"2na3pAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
